name: CI
on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ruby and Bundle Install
        uses: eregon/use-ruby-action@v1

        with:
          bundler-cache: true

      - name: Spec
        env:
          CI: true
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COVERAGE: true
          MINIMUM_COVERAGE: 80

        run: bundle exec rspec
